import React, { useEffect, useState, useSyncExternalStore } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { accessTokenKey, api, auth, clearTokens } from './api.js';
import './styles.css';

type Score = { overall: number; lead: number; advertising: number; seo: number; security: number };
type Finding = { id: string; severity: string; title: string; description: string; evidence: { value?: string }; recommendation: string };
type Audit = { id: string; status: string; progress: number; progressStage: string; score?: Score | null; findings?: Finding[] };
type Website = { id: string; name: string; url: string; domain: string; audits: Audit[] };
type Organization = { id: string; name: string };
const authSnapshot = () => Boolean(localStorage.getItem(accessTokenKey));
const subscribeAuth = (callback: () => void) => { window.addEventListener('leadguard-auth-changed', callback); return () => window.removeEventListener('leadguard-auth-changed', callback); };
function AuthRoute({ children }: { children: React.ReactNode }) { const authenticated = useSyncExternalStore(subscribeAuth, authSnapshot, () => false); return authenticated ? <>{children}</> : <Navigate to="/login" replace />; }
function Shell({ children }: { children: React.ReactNode }) { const authenticated = useSyncExternalStore(subscribeAuth, authSnapshot, () => false); return <main><nav><Link to="/dashboard">LeadGuard <small>OS / V6</small></Link>{authenticated && <button onClick={() => { clearTokens(); location.href = '/login'; }}>Log out</button>}</nav>{children}</main>; }
function Home() { const authenticated = useSyncExternalStore(subscribeAuth, authSnapshot, () => false); return <Shell><p className="eyebrow">WEBSITE DIAGNOSTIC INTELLIGENCE</p><h1>Find the places your website loses momentum.</h1><p className="lede">Lead, tracking, SEO, and security signals translated into decisions.</p><Link className="action" to={authenticated ? '/dashboard' : '/login'}>Enter workspace -&gt;</Link></Shell>; }
function Login() { const navigate = useNavigate(); const [register, setRegister] = useState(false); const [error, setError] = useState(''); return <Shell><div className="narrow"><p className="eyebrow">WORKSPACE ACCESS</p><h1>{register ? 'Create your workspace.' : 'Sign in to LeadGuard.'}</h1><form onSubmit={async (event) => { event.preventDefault(); setError(''); const data = new FormData(event.currentTarget); try { await auth(register ? '/auth/register' : '/auth/login', { email: data.get('email'), password: data.get('password'), ...(register ? { organizationName: data.get('organizationName') } : {}) }); navigate('/dashboard', { replace: true }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to authenticate'); } }}><label>Email<input name="email" type="email" required /></label>{register && <label>Organization<input name="organizationName" required /></label>}<label>Password<input name="password" type="password" minLength={12} required /></label>{error && <p role="alert" className="error">{error}</p>}<button className="action" type="submit">{register ? 'Create account' : 'Sign in'} -&gt;</button></form><button className="textButton" type="button" onClick={() => setRegister((value) => !value)}>{register ? 'Already have an account?' : 'Create an account'}</button></div></Shell>; }
function AddWebsite({ onAdded }: { onAdded: () => void }) { const [open, setOpen] = useState(false); const [error, setError] = useState(''); if (!open) return <button className="action" type="button" onClick={() => setOpen(true)}>+ Add website</button>; return <form className="add" onSubmit={async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); try { await api('/websites', { method: 'POST', body: JSON.stringify({ name: data.get('name'), url: data.get('url') }) }); setOpen(false); onAdded(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to add website'); } }}><label>Website name<input name="name" required /></label><label>Website URL<input name="url" type="url" required /></label>{error && <p className="error">{error}</p>}<button className="action" type="submit">Add website -&gt;</button></form>; }
function Dashboard() { const [websites, setWebsites] = useState<Website[]>([]); const [orgs, setOrgs] = useState<Organization[]>([]); const [active, setActive] = useState(''); const [error, setError] = useState(''); const load = async () => { try { const [sites, organization] = await Promise.all([api<Website[]>('/websites'), api<{ activeOrganizationId: string; organizations: Organization[] }>('/organizations')]); setWebsites(sites); setOrgs(organization.organizations); setActive(organization.activeOrganizationId); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load workspace'); } }; useEffect(() => { void load(); }, []); return <Shell><header className="row"><div><p className="eyebrow">ACTIVE WORKSPACE</p><h2>Diagnostic command center</h2></div><select aria-label="Active organization" value={active} onChange={async (event) => { const switched = await api<{ accessToken: string }>(`/organizations/${event.target.value}/switch`, { method: 'POST' }); localStorage.setItem(accessTokenKey, switched.accessToken); window.dispatchEvent(new Event('leadguard-auth-changed')); void load(); }}>{orgs.map((org) => <option value={org.id} key={org.id}>{org.name}</option>)}</select></header><AddWebsite onAdded={() => void load()} />{error && <p role="alert" className="error">{error}</p>}<section className="list"><h3>Websites</h3>{!websites.length ? <p className="muted">No websites yet.</p> : websites.map((site) => <article key={site.id}><div><strong>{site.name}</strong><span>{site.domain}</span></div><Link to={`/websites/${site.id}`}>Open -&gt;</Link></article>)}</section></Shell>; }
function WebsiteDetail() { const { id } = useParams(); const [site, setSite] = useState<Website>(); const [audit, setAudit] = useState<Audit>(); const [error, setError] = useState(''); const load = async () => { try { const value = await api<Website>(`/websites/${id}`); setSite(value); if (value.audits[0]) setAudit(value.audits[0]); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load website'); } }; useEffect(() => { void load(); }, [id]); useEffect(() => { if (!audit || ['COMPLETED', 'FAILED', 'PARTIAL', 'CANCELLED'].includes(audit.status)) return; const timer = window.setInterval(async () => { const progress = await api<Audit>(`/audits/${audit.id}/progress`); setAudit((current) => current ? { ...current, ...progress } : progress); if (['COMPLETED', 'FAILED', 'PARTIAL', 'CANCELLED'].includes(progress.status)) void load(); }, 1500); return () => window.clearInterval(timer); }, [audit?.id, audit?.status]); if (!site) return <Shell><p>{error || 'Loading...'}</p></Shell>; return <Shell><Link to="/dashboard">&lt;- Dashboard</Link><p className="eyebrow">WEBSITE</p><h2>{site.name}</h2><p className="muted">{site.url}</p>{audit && <AuditPanel audit={audit} />}<button className="action" type="button" onClick={async () => setAudit(await api<Audit>('/audits', { method: 'POST', body: JSON.stringify({ websiteId: site.id, idempotencyKey: `manual-${Date.now()}` }) }))}>Start audit -&gt;</button></Shell>; }
function AuditPanel({ audit }: { audit: Audit }) { const [detail, setDetail] = useState<Audit>(); useEffect(() => { if (['COMPLETED', 'PARTIAL'].includes(audit.status)) void api<Audit>(`/audits/${audit.id}`).then(setDetail); }, [audit]); const score = detail?.score; return <section className="audit"><div className="row"><div><p className="eyebrow">AUDIT {audit.status}</p><h3>{audit.progressStage} / {audit.progress}%</h3></div>{score && <strong className="score">{score.overall}</strong>}</div><progress max="100" value={audit.progress} />{score && <div className="scores">{[['Lead', score.lead], ['Ads', score.advertising], ['SEO', score.seo], ['Security', score.security]].map(([name, value]) => <div key={String(name)}><b>{name}</b><strong>{value}</strong></div>)}</div>}{detail?.findings?.map((finding) => <article className="finding" key={finding.id}><span className={`severity ${finding.severity}`}>{finding.severity}</span><h4>{finding.title}</h4><p>{finding.description}</p><small>Evidence: {finding.evidence?.value}</small><p><b>Recommendation:</b> {finding.recommendation}</p></article>)}</section>; }
function App() { return <BrowserRouter><Routes><Route path="/" element={<Home />} /><Route path="/login" element={<Login />} /><Route path="/dashboard" element={<AuthRoute><Dashboard /></AuthRoute>} /><Route path="/websites/:id" element={<AuthRoute><WebsiteDetail /></AuthRoute>} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></BrowserRouter>; }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
