import { db } from '@leadguard/database';
import { entitlementService } from '../entitlementService.js';

export interface BrandingConfig {
  logoUrl?: string;
  companyName?: string;
  website?: string;
  supportEmail?: string;
  primaryColor?: string;
  secondaryColor?: string;
  footer?: string;
}

function escapeHtml(str?: string | null): string {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function sanitizeHexColor(color?: string | null, fallback = '#6366f1'): string {
  if (!color) return fallback;
  const clean = color.trim();
  if (/^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(clean)) {
    return clean;
  }
  return fallback;
}

export class WhiteLabelService {
  async resolveBranding(
    organizationId: string,
    clientWorkspaceId?: string | null
  ): Promise<BrandingConfig> {
    const entitlement = await entitlementService.canUseWhiteLabel(organizationId);

    // If plan doesn't include white-label, return default LeadGuard OS branding
    if (!entitlement.allowed) {
      return {
        companyName: 'LeadGuard OS',
        website: 'https://leadguard.io',
        supportEmail: 'support@leadguard.io',
        primaryColor: '#6366f1',
        secondaryColor: '#10b981',
        footer: 'Powered by LeadGuard OS Diagnostic Engine',
      };
    }

    // 1. Check Client Workspace branding
    if (clientWorkspaceId) {
      const client = await db.clientWorkspace.findFirst({
        where: { id: clientWorkspaceId, organizationId },
      });
      if (client?.branding && typeof client.branding === 'object') {
        const cb = client.branding as BrandingConfig;
        return {
          companyName: cb.companyName || client.name,
          logoUrl: cb.logoUrl,
          website: cb.website,
          supportEmail: cb.supportEmail,
          primaryColor: sanitizeHexColor(cb.primaryColor, '#6366f1'),
          secondaryColor: sanitizeHexColor(cb.secondaryColor, '#10b981'),
          footer: cb.footer || `Prepared for ${client.name}`,
        };
      }
    }

    // 2. Fallback to Agency Organization name
    const org = await db.organization.findUnique({
      where: { id: organizationId },
    });

    return {
      companyName: org?.name || 'LeadGuard Agency Partner',
      primaryColor: '#6366f1',
      secondaryColor: '#10b981',
      footer: `Generated by ${org?.name || 'Agency'} Diagnostic Intelligence`,
    };
  }

  generateBrandedHtml(reportData: {
    title: string;
    auditDate: string;
    websiteUrl: string;
    overallScore: number;
    findingsCount: number;
    criticalFindings: number;
    branding: BrandingConfig;
  }): string {
    const { branding } = reportData;
    const primaryColor = sanitizeHexColor(branding.primaryColor, '#6366f1');

    const safeTitle = escapeHtml(reportData.title);
    const safeCompanyName = escapeHtml(branding.companyName || 'Diagnostic Report');
    const safeWebsite = escapeHtml(branding.website || '');
    const safeWebsiteUrl = escapeHtml(reportData.websiteUrl);
    const safeAuditDate = escapeHtml(reportData.auditDate);
    const safeFooter = escapeHtml(branding.footer || 'Confidential Client Diagnostic Report');
    const safeEmail = escapeHtml(branding.supportEmail || '');

    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${safeTitle} — ${safeCompanyName}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 0; padding: 40px; color: #1e293b; background: #fff; }
    .header { border-bottom: 2px solid ${primaryColor}; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }
    .title { font-size: 24px; font-weight: bold; color: ${primaryColor}; margin: 0; }
    .agencyName { font-size: 16px; color: #64748b; margin-top: 4px; }
    .scoreCard { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 24px; margin-bottom: 24px; text-align: center; }
    .scoreValue { font-size: 48px; font-weight: 800; color: ${primaryColor}; }
    .statsGrid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px; margin-bottom: 30px; }
    .statBox { background: #f1f5f9; padding: 16px; border-radius: 6px; }
    .footer { margin-top: 50px; border-top: 1px solid #e2e8f0; padding-top: 16px; font-size: 12px; color: #94a3b8; text-align: center; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1 class="title">${safeTitle}</h1>
      <div class="agencyName">${safeCompanyName}</div>
    </div>
    <div>${safeWebsite}</div>
  </div>

  <div class="scoreCard">
    <div>Overall Lead Health Score</div>
    <div class="scoreValue">${Number(reportData.overallScore)}/100</div>
    <div>Website: ${safeWebsiteUrl} | Date: ${safeAuditDate}</div>
  </div>

  <div class="statsGrid">
    <div class="statBox">
      <strong>Total Findings:</strong> ${Number(reportData.findingsCount)}
    </div>
    <div class="statBox">
      <strong>Critical Flaws:</strong> ${Number(reportData.criticalFindings)}
    </div>
  </div>

  <div class="footer">
    ${safeFooter}
    ${safeEmail ? ` | Contact: ${safeEmail}` : ''}
  </div>
</body>
</html>`;
  }
}

export const whiteLabelService = new WhiteLabelService();
