import { db } from '@leadguard/database';
import { entitlementService } from '../entitlementService.js';

export interface BrandingConfig {
  logoUrl?: string;
  companyName?: string;
  website?: string;
  supportEmail?: string;
  primaryColor?: string;
  secondaryColor?: string;
  footer?: string;
}

export class WhiteLabelService {
  async resolveBranding(
    organizationId: string,
    clientWorkspaceId?: string | null
  ): Promise<BrandingConfig> {
    const entitlement = await entitlementService.canUseWhiteLabel(organizationId);

    // If plan doesn't include white-label, return default LeadGuard OS branding
    if (!entitlement.allowed) {
      return {
        companyName: 'LeadGuard OS',
        website: 'https://leadguard.io',
        supportEmail: 'support@leadguard.io',
        primaryColor: '#6366f1',
        secondaryColor: '#10b981',
        footer: 'Powered by LeadGuard OS Diagnostic Engine',
      };
    }

    // 1. Check Client Workspace branding
    if (clientWorkspaceId) {
      const client = await db.clientWorkspace.findUnique({
        where: { id: clientWorkspaceId },
      });
      if (client?.branding && typeof client.branding === 'object') {
        const cb = client.branding as BrandingConfig;
        return {
          companyName: cb.companyName || client.name,
          logoUrl: cb.logoUrl,
          website: cb.website,
          supportEmail: cb.supportEmail,
          primaryColor: cb.primaryColor || '#6366f1',
          secondaryColor: cb.secondaryColor || '#10b981',
          footer: cb.footer || `Prepared for ${client.name}`,
        };
      }
    }

    // 2. Fallback to Agency Organization name
    const org = await db.organization.findUnique({
      where: { id: organizationId },
    });

    return {
      companyName: org?.name || 'LeadGuard Agency Partner',
      primaryColor: '#6366f1',
      secondaryColor: '#10b981',
      footer: `Generated by ${org?.name || 'Agency'} Diagnostic Intelligence`,
    };
  }

  generateBrandedHtml(reportData: {
    title: string;
    auditDate: string;
    websiteUrl: string;
    overallScore: number;
    findingsCount: number;
    criticalFindings: number;
    branding: BrandingConfig;
  }): string {
    const { branding } = reportData;
    const primaryColor = branding.primaryColor || '#6366f1';

    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${reportData.title} — ${branding.companyName || 'Diagnostic Report'}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 0; padding: 40px; color: #1e293b; background: #fff; }
    .header { border-bottom: 2px solid ${primaryColor}; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }
    .title { font-size: 24px; font-weight: bold; color: ${primaryColor}; margin: 0; }
    .agencyName { font-size: 16px; color: #64748b; margin-top: 4px; }
    .scoreCard { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 24px; margin-bottom: 24px; text-align: center; }
    .scoreValue { font-size: 48px; font-weight: 800; color: ${primaryColor}; }
    .statsGrid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px; margin-bottom: 30px; }
    .statBox { background: #f1f5f9; padding: 16px; border-radius: 6px; }
    .footer { margin-top: 50px; border-top: 1px solid #e2e8f0; padding-top: 16px; font-size: 12px; color: #94a3b8; text-align: center; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1 class="title">${reportData.title}</h1>
      <div class="agencyName">${branding.companyName || 'LeadGuard Agency Report'}</div>
    </div>
    <div>${branding.website || ''}</div>
  </div>

  <div class="scoreCard">
    <div>Overall Lead Health Score</div>
    <div class="scoreValue">${reportData.overallScore}/100</div>
    <div>Website: ${reportData.websiteUrl} | Date: ${reportData.auditDate}</div>
  </div>

  <div class="statsGrid">
    <div class="statBox">
      <strong>Total Findings:</strong> ${reportData.findingsCount}
    </div>
    <div class="statBox">
      <strong>Critical Flaws:</strong> ${reportData.criticalFindings}
    </div>
  </div>

  <div class="footer">
    ${branding.footer || 'Confidential Client Diagnostic Report'}
    ${branding.supportEmail ? ` | Contact: ${branding.supportEmail}` : ''}
  </div>
</body>
</html>`;
  }
}

export const whiteLabelService = new WhiteLabelService();
