import { describe, it, expect, beforeAll } from 'vitest';
import request from 'supertest';
import { db } from '@leadguard/database';
import { app } from '../../apps/api/src/server.js';
import { createAccessToken } from '../../apps/api/src/auth.js';
import { renderHtmlToPdf, generateReportHtml } from '../../apps/worker/src/report/pdfWorker.js';
import { LocalStorageProvider } from '@leadguard/shared/dist/server-only/report-storage.js';

/**
 * Regression suite for the "real PDF download" gap: PDF generation itself
 * (renderHtmlToPdf via Playwright, tests/reports/pdf-generation.test.ts) was
 * already real, but no route ever served the generated bytes back to a
 * customer — Report.pdfPath was set but nothing read it through an
 * authenticated or share-link download endpoint. This exercises the new
 * GET /reports/:id/pdf and GET /reports/share/:token/pdf routes end-to-end,
 * including the tenant-isolation and share-link permission checks the task
 * requires.
 */
describe('Report PDF download (authenticated + share-link)', () => {
  let orgAId: string;
  let orgBId: string;
  let reportId: string;
  let tokenA: string;
  let tokenB: string;

  async function createOrgWithReport(label: string, pdfStatus: string) {
    const org = await db.organization.create({
      data: { name: `PDF DL Org ${label} ${Date.now()}`, slug: `pdf-dl-${label.toLowerCase()}-${Date.now()}-${Math.random().toString(36).slice(2)}` },
    });
    const proPlan = await db.plan.upsert({
      where: { code: 'PRO' },
      create: {
        code: 'PRO',
        name: 'Pro',
        priceInPaise: 499900,
        currency: 'INR',
        entitlements: { auditsPerMonth: 100, websites: 5, monitoring: true, apiAccess: true, whiteLabel: true, reports: 50, prospectLimit: 100 },
      },
      update: {},
    });
    await db.subscription.create({ data: { organizationId: org.id, planId: proPlan.id, status: 'ACTIVE' } });

    const website = await db.website.create({
      data: {
        organizationId: org.id,
        name: `${label} Site`,
        url: 'https://example.com',
        normalizedUrl: 'https://example.com',
        domain: 'example.com',
      },
    });
    const audit = await db.audit.create({
      data: { organizationId: org.id, websiteId: website.id, status: 'COMPLETED' },
    });
    await db.auditScore.create({
      data: { auditId: audit.id, overall: 82, lead: 80, advertising: 78, seo: 85, security: 88 },
    });

    const report = await db.report.create({
      data: {
        organizationId: org.id,
        auditId: audit.id,
        title: `${label} Diagnostic Report`,
        status: 'READY',
        pdfStatus,
        snapshotData: { website: { url: website.url }, score: { overall: 82 }, findings: [], branding: { companyName: `${label} Co` } },
      },
    });

    const owner = await db.user.create({ data: { email: `pdf_dl_${label.toLowerCase()}_${Date.now()}@example.com`, passwordHash: 'hash' } });
    await db.organizationMember.create({ data: { organizationId: org.id, userId: owner.id, role: 'OWNER' } });
    const token = createAccessToken(owner.id, org.id);

    return { orgId: org.id, reportId: report.id, token };
  }

  beforeAll(async () => {
    const a = await createOrgWithReport('A', 'READY');
    orgAId = a.orgId;
    reportId = a.reportId;
    tokenA = a.token;

    const b = await createOrgWithReport('B', 'READY');
    orgBId = b.orgId;
    tokenB = b.token;

    // Render and store a real PDF for Org A's report — mirrors what
    // processPdfJob does, without requiring the BullMQ worker to actually
    // run in this test process.
    const html = generateReportHtml({
      title: 'Org A Diagnostic Report',
      auditDate: '2026-01-01',
      websiteUrl: 'https://example.com',
      overallScore: 82,
      findingsCount: 0,
      criticalFindings: 0,
      branding: { companyName: 'Org A Co', primaryColor: '#2563eb', secondaryColor: '#1e293b' },
    });
    const pdf = await renderHtmlToPdf(html);
    // Matches the default LocalStorageProvider() base dir getStorageProvider()
    // resolves to when REPORT_STORAGE isn't 'S3' — must be the same directory
    // the download route's getStorageProvider() call will read from.
    const storage = new LocalStorageProvider();
    const filename = `report_${reportId}_v1.pdf`;
    const savedPath = await storage.save(filename, pdf);
    await db.report.update({ where: { id: reportId }, data: { pdfPath: savedPath, pdfStatus: 'READY' } });
  }, 30_000);

  it('returns real PDF bytes with correct content-type and filename for the owning org', async () => {
    const res = await request(app)
      .get(`/api/v1/reports/${reportId}/pdf`)
      .set('Authorization', `Bearer ${tokenA}`);

    expect(res.status).toBe(200);
    expect(res.headers['content-type']).toContain('application/pdf');
    expect(res.headers['content-disposition']).toMatch(/filename="report_.*\.pdf"/);

    const buffer = Buffer.from(res.body);
    expect(buffer.subarray(0, 5).toString('utf-8')).toBe('%PDF-');
    expect(buffer.length).toBeGreaterThan(500);
  });

  it('rejects requests with no authentication', async () => {
    const res = await request(app).get(`/api/v1/reports/${reportId}/pdf`);
    expect(res.status).toBe(401);
  });

  it('does not let Org B download Org A\'s report PDF (tenant isolation)', async () => {
    const res = await request(app)
      .get(`/api/v1/reports/${reportId}/pdf`)
      .set('Authorization', `Bearer ${tokenB}`);
    expect(res.status).toBe(404);
    expect(res.body.error.code).toBe('REPORT_NOT_FOUND');
  });

  it('surfaces a not-ready PDF cleanly instead of returning corrupted/empty bytes', async () => {
    const notReady = await createOrgWithReport('C', 'GENERATING');
    const res = await request(app)
      .get(`/api/v1/reports/${notReady.reportId}/pdf`)
      .set('Authorization', `Bearer ${notReady.token}`);
    expect(res.status).toBe(409);
    expect(res.body.error.code).toBe('PDF_NOT_READY');
  });

  it('surfaces a FAILED generation cleanly rather than serving stale/fake content', async () => {
    const failed = await createOrgWithReport('D', 'FAILED');
    const res = await request(app)
      .get(`/api/v1/reports/${failed.reportId}/pdf`)
      .set('Authorization', `Bearer ${failed.token}`);
    expect(res.status).toBe(409);
    expect(res.body.error.code).toBe('PDF_NOT_READY');
  });

  describe('share-link PDF download', () => {
    it('serves the PDF via a valid share token with no authentication required', async () => {
      const share = await request(app)
        .post(`/api/v1/reports/${reportId}/share`)
        .set('Authorization', `Bearer ${tokenA}`)
        .send({});
      expect(share.status).toBe(201);
      const rawToken = share.body.data.rawToken as string;

      const res = await request(app).get(`/api/v1/reports/share/${rawToken}/pdf`);
      expect(res.status).toBe(200);
      expect(res.headers['content-type']).toContain('application/pdf');
      const buffer = Buffer.from(res.body);
      expect(buffer.subarray(0, 5).toString('utf-8')).toBe('%PDF-');
    });

    it('requires the correct password for a password-protected share link', async () => {
      const share = await request(app)
        .post(`/api/v1/reports/${reportId}/share`)
        .set('Authorization', `Bearer ${tokenA}`)
        .send({ password: 'correct-horse-battery-staple' });
      const rawToken = share.body.data.rawToken as string;

      const noPassword = await request(app).get(`/api/v1/reports/share/${rawToken}/pdf`);
      expect(noPassword.status).toBe(401);
      expect(noPassword.body.error.code).toBe('PASSWORD_REQUIRED');

      const wrongPassword = await request(app).get(`/api/v1/reports/share/${rawToken}/pdf?password=nope`);
      expect(wrongPassword.status).toBe(401);
      expect(wrongPassword.body.error.code).toBe('INVALID_PASSWORD');

      const correct = await request(app).get(
        `/api/v1/reports/share/${rawToken}/pdf?password=correct-horse-battery-staple`
      );
      expect(correct.status).toBe(200);
      expect(correct.headers['content-type']).toContain('application/pdf');
    });

    it('rejects a revoked share link', async () => {
      const share = await request(app)
        .post(`/api/v1/reports/${reportId}/share`)
        .set('Authorization', `Bearer ${tokenA}`)
        .send({});
      const rawToken = share.body.data.rawToken as string;
      const shareLinkId = share.body.data.shareLink.id as string;

      await request(app)
        .delete(`/api/v1/reports/${reportId}/share/${shareLinkId}`)
        .set('Authorization', `Bearer ${tokenA}`);

      const res = await request(app).get(`/api/v1/reports/share/${rawToken}/pdf`);
      expect(res.status).toBe(404);
      expect(res.body.error.code).toBe('SHARE_LINK_NOT_FOUND');
    });
  });

  it('preserves white-label branding in the rendered report HTML feeding the PDF', () => {
    const html = generateReportHtml({
      title: 'Branded Report',
      auditDate: '2026-01-01',
      websiteUrl: 'https://example.com',
      overallScore: 90,
      findingsCount: 2,
      criticalFindings: 0,
      branding: {
        companyName: 'Acme Agency Co',
        primaryColor: '#ff0000',
        secondaryColor: '#00ff00',
        footerText: 'Powered by Acme Agency',
      },
    });

    expect(html).toContain('Acme Agency Co');
    expect(html).toContain('Powered by Acme Agency');
    expect(html).toContain('#ff0000');
    expect(html).toContain('#00ff00');
    // Never HTML masquerading as the actual PDF artifact — this is a plain
    // HTML string, the PDF binary only comes from renderHtmlToPdf(html).
    expect(html.startsWith('<!DOCTYPE html>')).toBe(true);
  });
});
