import type { Finding, Severity, ScoreBreakdown } from './index.js';

export type ImpactInputs = { monthlyVisitors: number; conversionRate: number; averageLeadValue: number };
export type BusinessImpact = { kind: 'ESTIMATED'; confidence: 'LOW' | 'MEDIUM' | 'HIGH'; inputs: ImpactInputs; estimatedLeadLeakage: number; estimatedLostOpportunities: number; estimatedOpportunityLoss: number; methodology: string };
export type ExecutiveSummary = { headline: string; criticalCount: number; highCount: number; topProblems: string[]; priorityFixes: string[] };
const severityWeight: Record<Severity, number> = { CRITICAL: 4, HIGH: 3, MEDIUM: 2, LOW: 1, INFO: 0 };
export function rankFindings(findings: Finding[]) { return [...findings].sort((a, b) => severityWeight[b.severity] - severityWeight[a.severity] || b.scoreImpact - a.scoreImpact).slice(0, 3); }
export function buildBusinessImpact(findings: Finding[], inputs: ImpactInputs): BusinessImpact { const leakageRate = Math.min(0.5, findings.filter((f) => f.category === 'LEAD').reduce((sum, f) => sum + f.scoreImpact / 1000, 0)); const opportunities = inputs.monthlyVisitors * (inputs.conversionRate / 100) * leakageRate; return { kind: 'ESTIMATED', confidence: inputs.monthlyVisitors > 0 && inputs.averageLeadValue > 0 ? 'MEDIUM' : 'LOW', inputs, estimatedLeadLeakage: leakageRate, estimatedLostOpportunities: Math.round(opportunities), estimatedOpportunityLoss: Math.round(opportunities * inputs.averageLeadValue), methodology: 'Monthly visitors x conversion rate x detected lead leakage x average lead value. Inputs are user assumptions; output is an estimate.' }; }
export function buildExecutiveSummary(findings: Finding[], scores: ScoreBreakdown): ExecutiveSummary { const ranked = rankFindings(findings); return { headline: scores.overall >= 80 ? 'The website has a strong diagnostic baseline with targeted fixes available.' : 'The website has measurable issues that may interrupt discovery, trust, or lead capture.', criticalCount: findings.filter((f) => f.severity === 'CRITICAL').length, highCount: findings.filter((f) => f.severity === 'HIGH').length, topProblems: ranked.map((f) => f.title), priorityFixes: ranked.map((f) => f.recommendation) }; }
