import type { ScannerDefinition } from './types.js';

export const featureNames = [
  '4-Pillar Diagnostic Scan',
  'WhatsApp Link Scanner',
  'Click-to-Call Validator',
  'Contact Form & CTA Detector',
  'Meta Pixel Inspector',
  'GA4 / GTM Probe',
  'Google Indexing Check',
  'Canonical Scanner',
  'SSL/TLS + Mixed Content',
  'Security Headers',
  'OpenGraph Checker',
  'Lead Health Score',
  'Revenue Loss Estimator',
  'Business Impact Summary',
  'Funnel Leakage Simulator',
  'Revenue Scenario Planner',
  'Executive Intelligence Dashboard',
  'Zero-Intent WhatsApp Optimizer',
  'Cart Leakage Monitor',
  'Competitive Radar',
  'Express Fix',
  'Watchdog',
  'Pro / Agency / Enterprise Plans',
  'Razorpay Checkout',
  'Razorpay HMAC Webhook',
  'Client Workspace Management',
  '500-Site Prospect Hunter',
  'AI Cold Pitch Generator',
  'White-Label Reporting',
  'Diagnostic Studio Widget Generator',
  'Competitor Sabotage Radar',
  'Cryptographic Report Links',
  'White-Label PDF Reports',
  'Testimonials Wall',
  'Public REST API v1',
  'HMAC Webhooks',
  'OpenAPI / Swagger',
  'Role-Gated Admin',
  'Billing & Subscription Management',
  'Account Settings & Security Profile',
] as const;

export const featureIds = [
  'LG-001', 'LG-001', 'LG-003', 'LG-001', 'LG-006', 'LG-007', 'LG-010', 'LG-011',
  'LG-013', 'LG-014', 'LG-012', 'LG-016', 'LG-016', 'LG-016', 'LG-009', 'LG-008',
  'LG-029', 'LG-002', 'LG-021', 'LG-020', 'LG-032', 'LG-017', 'LG-031', 'LG-031',
  'LG-031', 'LG-024', 'LG-022', 'LG-023', 'LG-026', 'LG-028', 'LG-020', 'LG-025',
  'LG-026', 'LG-037', 'LG-033', 'LG-019', 'LG-033', 'LG-034', 'LG-035', 'LG-036',
] as const;

export const featureRegistry = featureNames.map((name, index) => ({
  key: `${featureIds[index]}-${index + 1}`,
  id: featureIds[index],
  name,
}));

export const scannerRegistry: ScannerDefinition[] = [
  {
    internalKey: 'WHATSAPP',
    featureId: 'LG-001',
    name: 'WhatsApp Link Scanner',
    category: 'LEAD',
    scope: 'PAGE',
    severityPolicy: 'HIGH',
    enabled: true,
  },
  {
    internalKey: 'WHATSAPP_SITE',
    featureId: 'LG-001',
    name: 'WhatsApp Site CTA Presence',
    category: 'LEAD',
    scope: 'WEBSITE',
    severityPolicy: 'MEDIUM',
    enabled: true,
  },
  {
    internalKey: 'TELEPHONE',
    featureId: 'LG-003',
    name: 'Click-to-Call Validator',
    category: 'LEAD',
    scope: 'PAGE',
    severityPolicy: 'HIGH',
    enabled: true,
  },
  {
    internalKey: 'TELEPHONE_SITE',
    featureId: 'LG-003',
    name: 'Click-to-Call Site CTA Presence',
    category: 'LEAD',
    scope: 'WEBSITE',
    severityPolicy: 'LOW',
    enabled: true,
  },
  {
    internalKey: 'FORMS_CTA',
    featureId: 'LG-001',
    name: 'Contact Form & CTA Detector',
    category: 'LEAD',
    scope: 'PAGE',
    severityPolicy: 'MEDIUM',
    enabled: true,
  },
  {
    internalKey: 'FORMS_SITE',
    featureId: 'LG-001',
    name: 'Contact Form Site Presence',
    category: 'LEAD',
    scope: 'WEBSITE',
    severityPolicy: 'MEDIUM',
    enabled: true,
  },
  {
    internalKey: 'META_PIXEL',
    featureId: 'LG-006',
    name: 'Meta Pixel Inspector',
    category: 'ADVERTISING',
    scope: 'WEBSITE',
    severityPolicy: 'LOW',
    enabled: true,
  },
  {
    internalKey: 'GA4',
    featureId: 'LG-007',
    name: 'GA4 Analytics Probe',
    category: 'ADVERTISING',
    scope: 'WEBSITE',
    severityPolicy: 'LOW',
    enabled: true,
  },
  {
    internalKey: 'GTM',
    featureId: 'LG-007',
    name: 'Google Tag Manager Probe',
    category: 'ADVERTISING',
    scope: 'WEBSITE',
    severityPolicy: 'LOW',
    enabled: true,
  },
  {
    internalKey: 'NOINDEX',
    featureId: 'LG-010',
    name: 'Google Indexing & Meta Robots Check',
    category: 'SEO',
    scope: 'PAGE',
    severityPolicy: 'HIGH',
    enabled: true,
  },
  {
    internalKey: 'CANONICAL',
    featureId: 'LG-011',
    name: 'Canonical Tag Scanner',
    category: 'SEO',
    scope: 'PAGE',
    severityPolicy: 'HIGH',
    enabled: true,
  },
  {
    internalKey: 'OPENGRAPH',
    featureId: 'LG-012',
    name: 'OpenGraph & Social Metadata Scanner',
    category: 'SEO',
    scope: 'PAGE',
    severityPolicy: 'LOW',
    enabled: true,
  },
  {
    internalKey: 'TLS',
    featureId: 'LG-013',
    name: 'SSL/TLS Certificate Validator',
    category: 'SECURITY',
    scope: 'WEBSITE',
    severityPolicy: 'CRITICAL',
    enabled: true,
  },
  {
    internalKey: 'MIXED_CONTENT',
    featureId: 'LG-013',
    name: 'Mixed Content Detector',
    category: 'SECURITY',
    scope: 'PAGE',
    severityPolicy: 'MEDIUM',
    enabled: true,
  },
  {
    internalKey: 'SECURITY_HEADERS',
    featureId: 'LG-014',
    name: 'Security Headers Analyzer',
    category: 'SECURITY',
    scope: 'WEBSITE',
    severityPolicy: 'MEDIUM',
    enabled: true,
  },
];
