-- AlterTable
ALTER TABLE "Audit" ADD COLUMN     "completedAt" TIMESTAMP(3),
ADD COLUMN     "durationMs" INTEGER,
ADD COLUMN     "findingsGenerated" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pagesDiscovered" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pagesFetched" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pagesScanned" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "queuedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "startedAt" TIMESTAMP(3);
